#!/usr/bin/env bash

set -euo pipefail

selected_path=$(find "$HOME" "$HOME"/personal "$HOME"/work -mindepth 1 -maxdepth 1 -type d | fzf)
session_name=$(basename "$selected_path" | tr . _)

if ! tmux has-session -t "$session_name" 2> /dev/null; then
    tmux new-session -s "$session_name" -c "$selected_path" -d
fi

TMUX=${TMUX-""}
if [[ -z "$TMUX" ]]; then
    tmux attach-session -t "$session_name"
else
    tmux switch-client -t "$session_name"
fi
